
import { ContentText, Language } from './types';

export const TEXT_CONTENT: Record<Language, ContentText> = {
  [Language.ENGLISH]: {
    navHome: "Home",
    navAbout: "About",
    navEvents: "Events",
    navContact: "Contact",
    heroTitle: "Language Exchange Prototype of Valencia",
    heroSubtitle: "Join our English-Spanish language exchange. Practice your speaking skills in a relaxed, friendly environment!",
    ctaButton: "Join Next Meetup",
    aboutTitle: "What is LEPV?",
    aboutText: "LEPV is a language exchange curated by students from ACIL in Valencia. Its mission is to UNITE and help the Valencian community practice their language skills and meet new people. All levels of proficiency are accepted!",
    detailsTitle: "Gathering Details",
    detailsWhenTxt: "Dates:",
    detailsWhen: "1st. 14th January, 18:30-19:30",
    detailsWhen2: "2nd. 21st January, 18:30-19:30",
    detailsWhen3: "3rd. 28th January, 18:30-19:30",
    detailsWhereTxt: "Locations:",
    detailsWhere: "1st. Santo Pastel Gran Via de les Germanies, 17, L'Eixample, 46006 València, Valencia",
    detailsWhere2: "2nd. Santo Pastel Gran Via de les Germanies, 17, L'Eixample, 46006 València, Valencia",
    detailsWhere3: "3rd. Santo Pastel Gran Via de les Germanies, 17, L'Eixample, 46006 València, Valencia",
    aiTitle: "Need a Conversation Starter?",
    aiDescription: "Don't know what to say? Let our AI generate a bilingual icebreaker question for you to practice with your partner.",
    aiButton: "Generate Icebreaker",
    footerRights: "© 2025 LEPV - Language Exchange Prototype of Valencia. All rights reserved.",
  },
  [Language.SPANISH]: {
    navHome: "Inicio",
    navAbout: "Nosotros",
    navEvents: "Eventos",
    navContact: "Contacto",
    heroTitle: "Intercambio de Idiomas de Valencia",
    heroSubtitle: "Únete a nuestro LEPV de idiomas inglés-español. ¡Practica tus habilidades para hablar en un ambiente relajado y amigable!",
    ctaButton: "Unirse la próxima reunión",
    aboutTitle: "¿Qué es LEPV?",
    aboutText: "LEPV es un programa de intercambio de idiomas organizado por estudiantes de ACIL en Valencia. Su misión es unir y ayudar a la comunidad valenciana a practicar sus habilidades lingüísticas y conocer gente nueva. ¡Se aceptan todos los niveles!",
    detailsTitle: "Detalles del Reunión",
    detailsWhen: "1.ª 14 de enero, 18:30-19:30",
    detailsWhen2: "2.ª 21 de enero, 18:30-19:30",
    detailsWhen3: "3.ª 28 de enero, 18:30-19:30",
    detailsWhenTxt: "Fechas:",
    detailsWhere: "1.ª Santo Pastel Gran Via de les Germanies, 17, L'Eixample, 46006 València, Valencia",
    detailsWhere2: "2.ª Santo Pastel Gran Via de les Germanies, 17, L'Eixample, 46006 València, Valencia",
    detailsWhere3: "3.ª Santo Pastel Gran Via de les Germanies, 17, L'Eixample, 46006 València, Valencia",
    detailsWhereTxt: "Ubicaciones:",
    aiTitle: "¿Necesitas un Tema de Conversación?",
    aiDescription: "¿No sabes qué decir? Deja que nuestra IA genere una pregunta rompehielos bilingüe para que practiques con tu compañero.",
    aiButton: "Generar Pregunta",
    footerRights: "© 2025 LEPV - Language Exchange Prototype de Valencia. Todos los derechos reservados.",
  },
};

export const NAV_LINKS = [
  { key: 'navHome', href: '#home' },
  { key: 'navAbout', href: '#about' },
  { key: 'navEvents', href: '#events' },
  { key: 'navContact', href: '#footer' },
] as const;
